name: ymrentals-api
services:
  - name: api
    type: web
    build:
      type: docker
      dockerfile: Dockerfile
    ports:
      - port: 8000
        protocol: http
    env:
      - name: NODE_ENV
        value: production
      - name: PORT
        value: "8000"
    health_check:
      http:
        path: /health
        port: 8000
    instance_type: nano
    regions:
      - fra
    scaling:
      min: 1
      max: 1
